# Generated by Django 2.0.5 on 2018-05-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20180513_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-amount',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(help_text='Amount allocated to this project.'),
        ),
    ]
