# Generated by Django 2.0.5 on 2018-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180522_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='impact',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Impact of this stakeholder on the project: 1 (low) - 5 (high)'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='influence',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Influence of this stakeholder: 1 (low) - 5 (high)'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='organization',
            field=models.CharField(blank=True, help_text='Company, business unit or department.', max_length=100),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='risk_tolerance',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Risk tolerance of this stakeholder: 1 (low) - 5 (high)'),
        ),
        migrations.AlterUniqueTogether(
            name='stakeholder',
            unique_together={('full_name', 'project')},
        ),
    ]
