# Generated by Django 2.0.5 on 2018-05-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180518_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Task',
        ),
    ]
