# Generated by Django 2.0.5 on 2018-05-23 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180522_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Role', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='project',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Stakeholder', verbose_name='stakeholder'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
