# Generated by Django 2.0.5 on 2018-05-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180519_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'order', 'name'], 'verbose_name': 'task'},
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='us_statuses',
        ),
    ]
