# Generated by Django 2.0.5 on 2018-05-16 14:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project_dashboard.core.utils.time


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180515_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('order', models.BigIntegerField(default=project_dashboard.core.utils.time.timestamp_ms, verbose_name='user order')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('default_owner_role', models.CharField(max_length=50, verbose_name="default owner's role")),
                ('is_contact_activated', models.BooleanField(default=True, verbose_name='active contact')),
                ('is_backlog_activated', models.BooleanField(default=True, verbose_name='active backlog panel')),
                ('is_kanban_activated', models.BooleanField(default=False, verbose_name='active kanban panel')),
                ('is_wiki_activated', models.BooleanField(default=True, verbose_name='active wiki panel')),
                ('is_issues_activated', models.BooleanField(default=True, verbose_name='active issues panel')),
                ('default_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='default options')),
                ('epic_statuses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='epic statuses')),
                ('us_statuses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='us statuses')),
                ('points', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='points')),
                ('task_statuses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='task statuses')),
                ('issue_statuses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='issue statuses')),
                ('issue_types', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='issue types')),
                ('priorities', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='priorities')),
                ('severities', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='severities')),
                ('roles', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='roles')),
                ('epic_custom_attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='epic custom attributes')),
                ('us_custom_attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='us custom attributes')),
                ('task_custom_attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='task custom attributes')),
                ('issue_custom_attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='issue custom attributes')),
            ],
            options={
                'verbose_name': 'project template',
                'verbose_name_plural': 'project templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='creation_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.ProjectTemplate', verbose_name='creation template'),
        ),
    ]
