# Generated by Django 2.0.5 on 2018-05-17 20:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180516_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Description of activity or task.', verbose_name='description')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is closed')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.Activity', verbose_name='parent activity')),
                ('predecessor', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='projects.Activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.TaskStatus')),
                ('successor', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='projects.Activity')),
            ],
            options={
                'verbose_name': 'activiy',
                'verbose_name_plural': 'activities',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('project', 'slug'), ('project', 'name')},
        ),
    ]
