# Generated by Django 2.0.5 on 2018-05-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0001_initial'),
        ('projects', '0007_auto_20180523_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, help_text='PMI process for this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmi.Process'),
        ),
    ]
