# Generated by Django 2.0.5 on 2018-05-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180523_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('due_date', models.DateField(blank=True, default=None, null=True, verbose_name='due date')),
                ('due_date_reason', models.TextField(blank=True, default='', verbose_name='reason for the due date')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(help_text='Detailed description of issue including effects on project.', verbose_name='description')),
                ('impact', models.TextField(blank=True, help_text='How will the issue impact the scope, schedule and/or cost of the project?', null=True, verbose_name='project impact')),
                ('importance', models.IntegerField(choices=[(5, 'Very High'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Very Low')], default=1, help_text='Importance from 1 (lowest) to 5 (highest)')),
                ('urgency', models.IntegerField(choices=[(5, 'Very High'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Very Low')], default=1, help_text='Urgency from 1 (lowest) to 5 (highest)')),
                ('priority', models.IntegerField()),
                ('resolution_plan', models.TextField(blank=True, help_text='Plan to resolve issue.', null=True)),
                ('resolved', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('progress', models.TextField(blank=True, help_text='Update on issue resolution (may not be edited later).', null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_note', to='projects.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='slug')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is closed')),
                ('color', models.CharField(default='#999999', max_length=20, verbose_name='color')),
            ],
            options={
                'verbose_name': 'issue status',
                'verbose_name_plural': 'issue statuses',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'created'], 'permissions': (('view_milestone', 'Can view milestone'),), 'verbose_name': 'task'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_statuses', to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned_to_me', to='projects.Stakeholder', verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_issues', to='projects.Stakeholder', verbose_name='business owner'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.IssueStatus', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='issue',
            name='task',
            field=models.ManyToManyField(help_text='Task(s) this issue affects or is related to.', related_name='issues', to='projects.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='issuestatus',
            unique_together={('project', 'name'), ('project', 'slug')},
        ),
    ]
