# Generated by Django 2.0.5 on 2018-05-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180524_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['priority', 'project', 'name']},
        ),
    ]
