# Generated by Django 2.0.5 on 2018-05-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180524_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, help_text='Person accountable for resolution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned_to_me', to='projects.Stakeholder', verbose_name='assigned to'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='importance',
            field=models.IntegerField(choices=[(5, 'Very High'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Very Low')], default=1, help_text='How CRITICAL is it to the project?'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, help_text='Stakeholder affected by / knowledgeable about this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_issues', to='projects.Stakeholder', verbose_name='business owner'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='urgency',
            field=models.IntegerField(choices=[(5, 'Very High'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Very Low')], default=1, help_text='How IMMEDIATELY is it needed?'),
        ),
        migrations.AlterField(
            model_name='issueprogress',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='projects.Issue'),
        ),
    ]
