# Generated by Django 2.0.5 on 2018-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180524_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='issues', to='projects.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(help_text='(CALCULATED)', null=True),
        ),
    ]
