# Generated by Django 2.0.5 on 2018-05-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180524_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.ManyToManyField(related_name='issues', to='projects.Category', verbose_name='categories'),
        ),
    ]
