# Generated by Django 2.0.5 on 2018-05-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180524_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='full_name',
        ),
    ]
