# Generated by Django 2.0.5 on 2018-05-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_stakeholder_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for Stakeholder URL.', max_length=250, verbose_name='slug'),
        ),
    ]
