# Generated by Django 2.0.5 on 2018-05-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180525_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['project', 'stakeholder__slug', 'stakeholder__user', 'stakeholder__email_address'], 'verbose_name': 'membership', 'verbose_name_plural': 'memberships'},
        ),
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
            preserve_default=False,
        ),
    ]
