# Generated by Django 2.0.5 on 2018-05-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180526_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('slug', 'project')},
        ),
    ]
