# Generated by Django 2.0.5 on 2018-05-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text="Used to build the process' URL.", max_length=100, unique=True, verbose_name='slug')),
                ('order', models.CharField(help_text='Process ID from the PMBOK Guide.', max_length=10, verbose_name='PMBOK ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('knowledge_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='pmi.KnowledgeArea', verbose_name='knowledge area')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='process_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='pmi.ProcessGroup', verbose_name='process group'),
        ),
    ]
