# Generated by Django 2.0.5 on 2018-05-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['process_group', 'order'], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
    ]
