# Generated by Django 2.0.5 on 2018-05-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearea',
            name='slug',
        ),
    ]
