# Generated by Django 2.0.5 on 2018-05-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projmgmt', '0002_remove_knowledgearea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='projmgmt.KnowledgeArea', verbose_name='knowledge area'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='projmgmt.ProcessGroup', verbose_name='process group'),
        ),
    ]
