# Generated by Django 2.0.5 on 2018-05-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projmgmt', '0003_auto_20180517_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['order'], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.CharField(default=1, help_text='Process ID from the PMBOK Guide.', max_length=10, verbose_name='PMBOK ID'),
            preserve_default=False,
        ),
    ]
