# Generated by Django 2.0.5 on 2018-05-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='If different from First Name + Last Name', max_length=255, verbose_name='Name of User'),
        ),
    ]
