# Generated by Django 2.0.5 on 2018-05-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('I', 'Internal'), ('E', 'External')], default='I', help_text='Relative to the project team.', max_length=1),
        ),
    ]
